projects:
  myapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: k3ixfb3pvjhuvdwz73ffu536jy
      endpoints:
        prod: >-
          https://xibqklsmkjg7je2eekzjrobpoa.appsync-api.us-east-1.amazonaws.com/graphql
