// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0d9c9638-f1c5-41f4-96e1-f184f91c8441",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_enImjfoer",
    "aws_user_pools_web_client_id": "40ji7on3ehntp0igi5sh4o627m",
    "aws_appsync_graphqlEndpoint": "https://xibqklsmkjg7je2eekzjrobpoa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
